package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/liviudnicoara/go-graphql-poc/shared"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*shared.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// UsersByID is the resolver for the usersByID field.
func (r *queryResolver) UsersByID(ctx context.Context, id string) (*shared.User, error) {
	panic(fmt.Errorf("not implemented: UsersByID - usersByID"))
}
