// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package shared

type CreateTodo struct {
	Text   string `json:"text"`
	DueAt  string `json:"dueAt"`
	UserID string `json:"userID"`
}

type Todo struct {
	ID          string  `json:"id"`
	Text        string  `json:"text"`
	Done        bool    `json:"done"`
	CreatedAt   string  `json:"createdAt"`
	CompletedAt *string `json:"completedAt,omitempty"`
	DueAt       string  `json:"dueAt"`
	UserID      string  `json:"userID"`
}

type TodoMutationResponse struct {
	Sucess  bool    `json:"sucess"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Todo    *Todo   `json:"todo,omitempty"`
}

type UpdateTodo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	DueAt  string `json:"dueAt"`
	UserID string `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
