// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package shared

import (
	"time"
)

type CreateTodo struct {
	Text   string    `json:"text"`
	DueAt  time.Time `json:"dueAt"`
	UserID string    `json:"userID"`
}

type Todo struct {
	ID          string     `json:"id"`
	Text        string     `json:"text"`
	Done        bool       `json:"done"`
	CreatedAt   time.Time  `json:"createdAt"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	DueAt       time.Time  `json:"dueAt"`
	UserID      string     `json:"userID"`
}

type TodoMutationResponse struct {
	Sucess  bool    `json:"sucess"`
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Todo    *Todo   `json:"todo,omitempty"`
}

type UpdateTodo struct {
	ID     string    `json:"id"`
	Text   string    `json:"text"`
	Done   bool      `json:"done"`
	DueAt  time.Time `json:"dueAt"`
	UserID string    `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
