// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package shared

type CmdResponse struct {
	IsSucessfull bool    `json:"isSucessfull"`
	Error        *string `json:"error,omitempty"`
}

type CreateTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userID"`
}

type Todo struct {
	ID          string  `json:"id"`
	Text        string  `json:"text"`
	Done        bool    `json:"done"`
	CreatedAt   string  `json:"createdAt"`
	CompletedAt *string `json:"completedAt,omitempty"`
	UserID      string  `json:"userID"`
}

type UpdateTodo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	UserID string `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
